# Stage 1: Build stage
FROM node:22-alpine AS build

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy application code
COPY . .

# Build environment variables (can be overridden during docker build)
ARG REACT_APP_BASE_URL
ARG REACT_APP_CFR_WEB_URL
ARG REACT_APP_INSIGHT_WEB_URL
ARG REACT_APP_COACHING_WEB_URL
ARG REACT_APP_PASSWORD_HASH_KEY
ARG REACT_APP_CRYPTR_SECRET_KEY
ARG REACT_APP_GA_TRACKING_ID
ARG REACT_APP_ORG_SUCCESS_DELAY_TIME
ARG REACT_APP_ENCRYPTION_ALGM
ARG REACT_APP_ENCRYPTION_SALT

ENV REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
ENV REACT_APP_CFR_WEB_URL=${REACT_APP_CFR_WEB_URL}
ENV REACT_APP_INSIGHT_WEB_URL=${REACT_APP_INSIGHT_WEB_URL}
ENV REACT_APP_COACHING_WEB_URL=${REACT_APP_COACHING_WEB_URL}
ENV REACT_APP_PASSWORD_HASH_KEY=${REACT_APP_PASSWORD_HASH_KEY}
ENV REACT_APP_CRYPTR_SECRET_KEY=${REACT_APP_CRYPTR_SECRET_KEY}
ENV REACT_APP_GA_TRACKING_ID=${REACT_APP_GA_TRACKING_ID}
ENV REACT_APP_ORG_SUCCESS_DELAY_TIME=${REACT_APP_ORG_SUCCESS_DELAY_TIME}
ENV REACT_APP_ENCRYPTION_ALGM=${REACT_APP_ENCRYPTION_ALGM}
ENV REACT_APP_ENCRYPTION_SALT=${REACT_APP_ENCRYPTION_SALT}

# Build static production assets into build/ directory
RUN npm run build

# Stage 2: Serve stage with Nginx
FROM nginx:1.25-alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
